### ISSUE TITLE
Lies lmao

### ISSUE THREAD

**Issue by breadythebread** [reputationdev/FireFly#1]
Here is a list of every lie in the readme:
![image_2022-12-31_120024741](https://user-images.githubusercontent.com/36639283/210150609-56dbb6ab-7931-4ff0-b75e-5f2aa5d5be47.png)
Starting out, both of the accounts in that screenshot are reputation/omen, here is him DMing me from the Omen account that reputation is his new account, 
![image_2022-12-31_120110374](https://user-images.githubusercontent.com/36639283/210150622-348174f2-1143-40f9-99eb-3aebab1ecde2.png)

"There are currently no other official ways to contact me or any other firefly developers/staff members."
His Omen account even says "FireFly > Developer (Resigned Recently)", he is not a firefly staff, he sold ownership.

"Recently the project was sold by ThePython to "Remixed" without my knowlage, permission or consent."
He gave ownership to Python, knowingly, which means he no longer can do anything about it, nor does anyone need his permission for Python to sell it to whoever he wants, meaning no issues with Remixed buying it. Also, knowledge not knowlage.

 Also the original FireFly repository is more proof, he gave ownership of that to ThePython, and when i explained all of this to him, this was his response:
![image_2022-12-31_120402562](https://user-images.githubusercontent.com/36639283/210150696-a0cf0d35-4cca-4913-9e9e-0f68108e354c.png)

DMCA Takedown submitted :)

**Comment by reputationdev** [comment]
Don't be so petty ok? You know it isnt your code. you didnt write any of it. and you dont own any of the rights to it.

**Comment by breadythebread** [comment]
> Don't be so petty ok? You know it isnt your code. you didnt write any of it. and you dont own any of the rights to it.

you sold it, you're just mad ☠️🤣

**Comment by reputationdev** [comment]
> > Don't be so petty ok? You know it isnt your code. you didnt write any of it. and you dont own any of the rights to it.
> 
> you sold it, you're just mad ☠️🤣

I didnt sell it? Seth sold it with 0 permission at all.

**Comment by breadythebread** [comment]
You gave him owner, which gives him permission. And you said yourself firefly is dead, and specifically took down the auth servers because of that so
